var BASE_URL = process.env.BASE_URL || 'https://webhookmail.onrender.com';

function esc(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function landingPage() {
  return [
    '<!DOCTYPE html><html lang="en"><head>',
    '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>WebhookMail - Forward Webhooks to Email Instantly | Free Webhook to Email</title>',
    '<meta name="description" content="Forward any webhook to your email inbox instantly. No code required. Free tier with 50 webhooks/month. Works with Stripe, GitHub, Shopify, and any webhook source.">',
    '<meta name="keywords" content="webhook to email, webhook forwarder, webhook notifications, webhook monitor, stripe webhook email, github webhook email">',
    '<meta property="og:title" content="WebhookMail - Forward Webhooks to Email Instantly">',
    '<meta property="og:description" content="Forward any webhook to your email. Instant setup, no code required. Free tier included.">',
    '<meta property="og:type" content="website">',
    '<meta property="og:url" content="' + BASE_URL + '">',
    '<meta name="twitter:card" content="summary">',
    '<link rel="canonical" href="' + BASE_URL + '">',
    '<link rel="icon" type="image/svg+xml" href="/favicon.svg">',
    '<link rel="manifest" href="/manifest.json">',
    '<style>',
    '*{margin:0;padding:0;box-sizing:border-box}',
    ':root{--bg:#09090b;--surface:#18181b;--border:#27272a;--border-h:#3f3f46;--text:#e4e4e7;--muted:#a1a1aa;--dim:#71717a;--accent:#818cf8;--accent-h:#6366f1;--accent-deep:#4f46e5;--green:#22c55e}',
    'body{font-family:system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:var(--bg);color:var(--text);-webkit-font-smoothing:antialiased}',
    '',
    '/* Hero */',
    '.hero{text-align:center;padding:100px 20px 48px;position:relative;overflow:hidden}',
    '.hero::before{content:"";position:absolute;top:-50%;left:50%;transform:translateX(-50%);width:800px;height:800px;background:radial-gradient(circle,rgba(99,102,241,0.08) 0%,transparent 70%);pointer-events:none}',
    '.badge{display:inline-block;padding:6px 14px;background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);border-radius:20px;font-size:13px;color:var(--accent);margin-bottom:24px;letter-spacing:0.3px}',
    '.hero h1{font-size:clamp(2.2rem,5vw,3.4rem);font-weight:800;line-height:1.15;margin-bottom:16px;letter-spacing:-0.02em}',
    '.hero h1 span{background:linear-gradient(135deg,#818cf8,#6366f1,#4f46e5);-webkit-background-clip:text;-webkit-text-fill-color:transparent}',
    '.hero .sub{font-size:1.15rem;color:var(--muted);max-width:480px;margin:0 auto 40px;line-height:1.6}',
    '',
    '/* Form */',
    '.form-wrap{max-width:440px;margin:0 auto 64px;position:relative}',
    '.form{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:28px}',
    '.form input{width:100%;padding:13px 16px;border:1px solid var(--border);border-radius:10px;background:var(--bg);color:var(--text);font-size:15px;margin-bottom:12px;transition:border 0.15s}',
    '.form input:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(99,102,241,0.15)}',
    '.form input::placeholder{color:var(--dim)}',
    '.cta{width:100%;padding:14px;background:linear-gradient(135deg,var(--accent-h),var(--accent-deep));color:white;border:none;border-radius:10px;font-size:15px;font-weight:700;cursor:pointer;transition:transform 0.1s,box-shadow 0.15s;letter-spacing:0.3px}',
    '.cta:hover{transform:translateY(-1px);box-shadow:0 4px 16px rgba(99,102,241,0.3)}',
    '.cta:active{transform:translateY(0)}',
    '.cta:disabled{opacity:0.6;cursor:not-allowed;transform:none}',
    '.result{display:none;margin-top:20px;padding:20px;background:var(--bg);border:1px solid var(--border);border-radius:12px;animation:fadeIn 0.3s ease}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}',
    '.result-label{font-size:12px;color:var(--dim);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px}',
    '.result-url{display:flex;align-items:center;gap:8px;margin-bottom:16px}',
    '.result-url code{flex:1;color:var(--accent);word-break:break-all;font-size:13px;font-family:"SF Mono",SFMono-Regular,Consolas,monospace}',
    '.copy-btn{background:var(--border);border:1px solid var(--border-h);color:var(--text);padding:6px 12px;border-radius:6px;cursor:pointer;font-size:12px;font-weight:600;transition:background 0.15s;white-space:nowrap}',
    '.copy-btn:hover{background:var(--border-h)}',
    '.copy-btn.copied{background:var(--green);border-color:var(--green);color:var(--bg)}',
    '.note{font-size:12px;color:var(--dim);text-align:center;margin-top:12px}',
    '',
    '/* Integrations */',
    '.integrations{text-align:center;padding:0 20px 48px}',
    '.integrations p{color:var(--dim);font-size:13px;text-transform:uppercase;letter-spacing:1px;margin-bottom:16px}',
    '.logos{display:flex;gap:32px;justify-content:center;flex-wrap:wrap;opacity:0.5}',
    '.logos span{font-size:14px;font-weight:600;color:var(--muted)}',
    '',
    '/* How it works */',
    '.how{max-width:640px;margin:0 auto;padding:64px 20px}',
    '.how h2{text-align:center;font-size:2rem;font-weight:800;margin-bottom:40px;letter-spacing:-0.02em}',
    '.step{display:flex;gap:20px;margin-bottom:32px;align-items:flex-start}',
    '.sn{background:linear-gradient(135deg,var(--accent-h),var(--accent-deep));color:white;width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:15px;flex-shrink:0}',
    '.st h4{font-size:16px;margin-bottom:4px;font-weight:700}',
    '.st p{color:var(--muted);font-size:14px;line-height:1.5}',
    '',
    '/* Features */',
    '.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;max-width:860px;margin:0 auto 64px;padding:0 20px}',
    '.feat{background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:24px;transition:border 0.2s}',
    '.feat:hover{border-color:var(--border-h)}',
    '.feat-icon{font-size:24px;margin-bottom:8px}',
    '.feat h3{font-size:15px;font-weight:700;margin-bottom:6px}',
    '.feat p{color:var(--muted);font-size:13px;line-height:1.5}',
    '',
    '/* Pricing */',
    '.pricing{text-align:center;padding:64px 20px}',
    '.pricing h2{font-size:2rem;font-weight:800;margin-bottom:12px;letter-spacing:-0.02em}',
    '.pricing .sub{color:var(--muted);margin-bottom:40px;font-size:15px}',
    '.plans{display:flex;gap:20px;justify-content:center;flex-wrap:wrap}',
    '.plan{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:32px;width:300px;text-align:left;transition:border 0.2s}',
    '.plan.pro{border-color:var(--accent);position:relative}',
    '.plan.pro::after{content:"POPULAR";position:absolute;top:-10px;right:20px;background:var(--accent-h);color:white;font-size:11px;font-weight:700;padding:4px 10px;border-radius:6px;letter-spacing:0.5px}',
    '.plan h3{font-size:1.2rem;margin-bottom:4px;font-weight:700}',
    '.plan .price{font-size:2.5rem;font-weight:800;background:linear-gradient(135deg,var(--accent),var(--accent-h));-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:4px}',
    '.plan .period{color:var(--dim);font-size:13px;margin-bottom:20px}',
    '.plan ul{list-style:none;margin-bottom:24px}',
    '.plan li{padding:6px 0;color:var(--muted);font-size:14px}',
    '.plan li::before{content:"\\2713\\00a0 ";color:var(--green);font-weight:700}',
    '.plan-btn{display:block;width:100%;padding:12px;border-radius:10px;text-align:center;font-weight:700;font-size:14px;cursor:pointer;text-decoration:none;transition:all 0.15s;border:none}',
    '.plan-btn.free{background:var(--bg);border:1px solid var(--border);color:var(--text)}',
    '.plan-btn.free:hover{border-color:var(--border-h)}',
    '.plan-btn.pro{background:linear-gradient(135deg,var(--accent-h),var(--accent-deep));color:white}',
    '.plan-btn.pro:hover{transform:translateY(-1px);box-shadow:0 4px 12px rgba(99,102,241,0.3)}',
    '',
    '/* Footer */',
    'footer{text-align:center;padding:48px 20px;border-top:1px solid var(--border);color:var(--dim);font-size:13px}',
    'footer a{color:var(--muted);text-decoration:none}',
    '</style></head><body>',
    '',
    '<div class="hero">',
    '<div class="badge">&#9889; No code. No server. No signup.</div>',
    '<h1>Forward <span>webhooks</span><br>to your email</h1>',
    '<p class="sub">Get instant email notifications for every webhook. Works with any service. Set up in 10 seconds.</p>',
    '</div>',
    '',
    '<div class="form-wrap">',
    '<div class="form" id="f">',
    '<input type="email" id="e" placeholder="your@email.com" required autocomplete="email">',
    '<input type="text" id="n" placeholder="Endpoint name (optional)" autocomplete="off">',
    '<button class="cta" id="btn" onclick="go()">Create Free Endpoint &rarr;</button>',
    '<div class="result" id="r">',
    '<div class="result-label">Webhook URL</div>',
    '<div class="result-url"><code id="wu"></code><button class="copy-btn" id="cb" onclick="copyUrl()">Copy</button></div>',
    '<div class="result-label">Dashboard</div>',
    '<div class="result-url"><code id="du"></code></div>',
    '</div>',
    '<p class="note">Free: 50 webhooks/month. No credit card required.</p>',
    '</div></div>',
    '',
    '<div class="integrations">',
    '<p>Works with any webhook source</p>',
    '<div class="logos"><span>Stripe</span><span>GitHub</span><span>Shopify</span><span>Slack</span><span>Twilio</span><span>Zapier</span><span>Linear</span></div>',
    '</div>',
    '',
    '<div class="how"><h2>How It Works</h2>',
    '<div class="step"><div class="sn">1</div><div class="st"><h4>Create an endpoint</h4><p>Enter your email and get a unique webhook URL. Takes 10 seconds.</p></div></div>',
    '<div class="step"><div class="sn">2</div><div class="st"><h4>Point your service</h4><p>Use the URL as a webhook destination in Stripe, GitHub, Slack, or any service.</p></div></div>',
    '<div class="step"><div class="sn">3</div><div class="st"><h4>Get email notifications</h4><p>Every webhook hit sends a formatted email with the full payload, headers, and metadata.</p></div></div>',
    '</div>',
    '',
    '<div class="features">',
    '<div class="feat"><div class="feat-icon">&#128279;</div><h3>Universal Compatibility</h3><p>Works with any HTTP webhook. POST, PUT, GET &mdash; all methods supported.</p></div>',
    '<div class="feat"><div class="feat-icon">&#128231;</div><h3>Formatted Emails</h3><p>Clean, readable emails with syntax-highlighted JSON payloads and request metadata.</p></div>',
    '<div class="feat"><div class="feat-icon">&#128202;</div><h3>Live Dashboard</h3><p>View webhook history, inspect payloads, and track monthly usage in real time.</p></div>',
    '<div class="feat"><div class="feat-icon">&#128274;</div><h3>No Signup Required</h3><p>Just enter your email. No accounts, no passwords, no OAuth. Start in seconds.</p></div>',
    '<div class="feat"><div class="feat-icon">&#9889;</div><h3>Instant Delivery</h3><p>Webhooks are processed and forwarded to your email in under 2 seconds.</p></div>',
    '<div class="feat"><div class="feat-icon">&#128736;</div><h3>Developer Friendly</h3><p>Full REST API. Create endpoints and query logs programmatically.</p></div>',
    '</div>',
    '',
    '<div class="pricing" id="pricing">',
    '<h2>Simple Pricing</h2>',
    '<p class="sub">Start free. Upgrade when you need more.</p>',
    '<div class="plans">',
    '<div class="plan">',
    '<h3>Free</h3><div class="price">$0</div><div class="period">forever</div>',
    '<ul><li>50 webhooks/month</li><li>1 endpoint</li><li>Email forwarding</li><li>7-day log history</li><li>Dashboard access</li></ul>',
    '<a href="#" class="plan-btn free" onclick="document.getElementById(\'e\').focus();return false">Get Started</a>',
    '</div>',
    '<div class="plan pro">',
    '<h3>Pro</h3><div class="price">$3</div><div class="period">per month</div>',
    '<ul><li>Unlimited webhooks</li><li>Unlimited endpoints</li><li>Email forwarding</li><li>30-day log history</li><li>Priority delivery</li><li>Webhook replay</li></ul>',
    '<button class="plan-btn pro" disabled>Coming Soon</button>',
    '</div></div></div>',
    '',
    '<footer>',
    '<p>WebhookMail &copy; 2026</p>',
    '</footer>',
    '',
    '<script>',
    'async function go(){',
    'var btn=document.getElementById("btn"),e=document.getElementById("e").value,n=document.getElementById("n").value;',
    'if(!e){document.getElementById("e").focus();return}',
    'btn.disabled=true;btn.textContent="Creating...";',
    'try{',
    'var r=await fetch("/api/endpoints",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,name:n})});',
    'var d=await r.json();',
    'if(d.error){alert(d.error);btn.disabled=false;btn.textContent="Create Free Endpoint \\u2192";return}',
    'document.getElementById("wu").textContent=d.webhookUrl;',
    'document.getElementById("du").innerHTML=\'<a href="\'+d.dashboardUrl+\'" style="color:#818cf8">\'+d.dashboardUrl+\'</a>\';',
    'document.getElementById("r").style.display="block";',
    'btn.textContent="\\u2713 Created!";btn.style.background="var(--green)";',
    '}catch(err){alert("Error: "+err.message);btn.disabled=false;btn.textContent="Create Free Endpoint \\u2192"}}',
    'function copyUrl(){',
    'var t=document.getElementById("wu").textContent,b=document.getElementById("cb");',
    'navigator.clipboard.writeText(t);b.textContent="Copied!";b.classList.add("copied");',
    'setTimeout(function(){b.textContent="Copy";b.classList.remove("copied")},2000)}',
    '</script></body></html>',
  ].join('\n');
}

export function dashboardPage(endpoint, logs, monthly) {
  var rows = logs.map(function(l) {
    var body = l.body || '';
    try { body = JSON.stringify(JSON.parse(body), null, 2); } catch (e) {}
    return [
      '<tr>',
      '<td class="td"><span class="time">' + esc(l.created_at) + '</span></td>',
      '<td class="td"><span class="method">' + esc(l.method) + '</span></td>',
      '<td class="td"><span class="ip">' + esc(l.source_ip) + '</span></td>',
      '<td class="td"><details><summary class="body-preview">' + esc(body).slice(0, 80) + '</summary><pre class="body-full">' + esc(body) + '</pre></details></td>',
      '</tr>',
    ].join('');
  }).join('');

  var emptyRow = '<tr><td colspan="4" class="empty">No webhooks received yet. Send a request to the webhook URL above to get started.</td></tr>';

  var tierBadge = endpoint.tier === 'pro'
    ? '<span style="background:var(--accent);color:white;padding:3px 10px;border-radius:6px;font-size:12px;font-weight:700">PRO</span>'
    : '<span style="background:var(--border);color:var(--muted);padding:3px 10px;border-radius:6px;font-size:12px;font-weight:700">FREE</span>';

  return [
    '<!DOCTYPE html><html lang="en"><head>',
    '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>' + esc(endpoint.name || 'Dashboard') + ' - WebhookMail</title>',
    '<link rel="icon" type="image/svg+xml" href="/favicon.svg">',
    '<style>',
    ':root{--bg:#09090b;--surface:#18181b;--border:#27272a;--border-h:#3f3f46;--text:#e4e4e7;--muted:#a1a1aa;--dim:#71717a;--accent:#818cf8;--green:#22c55e}',
    '*{margin:0;padding:0;box-sizing:border-box}',
    'body{font-family:system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text);padding:24px;-webkit-font-smoothing:antialiased}',
    '.wrap{max-width:960px;margin:0 auto}',
    '.header{display:flex;align-items:center;gap:12px;margin-bottom:24px;flex-wrap:wrap}',
    '.header h1{font-size:1.4rem;font-weight:700}',
    '.back{color:var(--accent);text-decoration:none;font-size:14px}',
    '.url-bar{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:14px 18px;margin-bottom:20px;font-family:"SF Mono",Consolas,monospace;font-size:14px;color:var(--accent);word-break:break-all;display:flex;align-items:center;gap:12px}',
    '.url-bar span{flex:1}',
    '.copy-btn{background:var(--border);border:1px solid var(--border-h);color:var(--text);padding:6px 14px;border-radius:6px;cursor:pointer;font-size:12px;font-weight:600;white-space:nowrap}',
    '.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:28px}',
    '.stat{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:16px}',
    '.stat .label{color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px}',
    '.stat .val{font-size:1.6rem;font-weight:800;color:var(--accent)}',
    '.stat .val.sm{font-size:14px}',
    'h2{font-size:1.1rem;margin-bottom:14px;font-weight:700}',
    'table{width:100%;border-collapse:collapse}',
    'th{text-align:left;padding:10px 12px;color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid var(--border-h)}',
    '.td{padding:10px 12px;border-bottom:1px solid var(--border);font-size:13px;vertical-align:top}',
    '.time{color:var(--dim)}',
    '.method{background:var(--accent);color:white;padding:2px 8px;border-radius:5px;font-size:11px;font-weight:700}',
    '.ip{color:var(--dim);font-family:monospace;font-size:12px}',
    '.body-preview{color:var(--muted);font-size:12px;cursor:pointer;font-family:monospace;max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.body-full{margin-top:8px;font-size:12px;max-height:200px;overflow:auto;color:var(--text);white-space:pre-wrap}',
    '.empty{padding:40px;text-align:center;color:var(--dim)}',
    'footer{text-align:center;margin-top:40px;color:var(--dim);font-size:13px}',
    'footer a{color:var(--muted);text-decoration:none}',
    '</style></head><body>',
    '<div class="wrap">',
    '<div class="header"><a href="/" class="back">&larr; WebhookMail</a><h1>' + esc(endpoint.name || 'Webhook Dashboard') + '</h1>' + tierBadge + '</div>',
    '<div class="url-bar"><span>POST ' + BASE_URL + '/hook/' + esc(endpoint.id) + '</span><button class="copy-btn" onclick="navigator.clipboard.writeText(\'' + BASE_URL + '/hook/' + esc(endpoint.id) + '\');this.textContent=\'Copied!\';setTimeout(()=>this.textContent=\'Copy\',2000)">Copy</button></div>',
    '<div class="stats">',
    '<div class="stat"><div class="label">This Month</div><div class="val">' + monthly + (endpoint.tier === 'free' ? '<span style="color:var(--dim);font-size:13px;font-weight:400"> / 50</span>' : '') + '</div></div>',
    '<div class="stat"><div class="label">All Time</div><div class="val">' + endpoint.webhook_count + '</div></div>',
    '<div class="stat"><div class="label">Plan</div><div class="val sm">' + esc(endpoint.tier).toUpperCase() + '</div></div>',
    '<div class="stat"><div class="label">Email</div><div class="val sm">' + esc(endpoint.email) + '</div></div>',
    '</div>',
    '<h2>Recent Webhooks</h2>',
    '<table><thead><tr><th>Time</th><th>Method</th><th>Source</th><th>Body</th></tr></thead>',
    '<tbody>' + (rows || emptyRow) + '</tbody></table>',
    '<footer><a href="/">WebhookMail</a> &copy; 2026</footer>',
    '</div></body></html>',
  ].join('\n');
}
