const BASE_URL = process.env.BASE_URL || 'https://webhookmail.onrender.com';

function esc(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function landingPage() {
  return [
    '<!DOCTYPE html><html lang="en"><head>',
    '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>WebhookMail - Forward Webhooks to Email Instantly | Free Webhook to Email</title>',
    '<meta name="description" content="Forward any webhook to your email inbox instantly. No code required. Free tier with 50 webhooks/month. Works with Stripe, GitHub, Shopify, Slack, and any webhook source.">',
    '<meta name="keywords" content="webhook to email, webhook forwarder, webhook notifications, webhook monitor, stripe webhook email, github webhook email, webhook testing">',
    '<meta property="og:title" content="WebhookMail - Forward Webhooks to Email Instantly">',
    '<meta property="og:description" content="Forward any webhook to your email. Instant setup, no code required. Free tier included.">',
    '<meta property="og:type" content="website">',
    '<meta property="og:url" content="' + BASE_URL + '">',
    '<meta name="twitter:card" content="summary">',
    '<meta name="twitter:title" content="WebhookMail - Webhooks to Email">',
    '<meta name="twitter:description" content="Forward any webhook to your email inbox. Free, instant, no code required.">',
    '<link rel="canonical" href="' + BASE_URL + '">',
    '<link rel="icon" type="image/svg+xml" href="/favicon.svg">',
    '<link rel="manifest" href="/manifest.json">',
    '<style>',
    '*{margin:0;padding:0;box-sizing:border-box}',
    'body{font-family:system-ui,-apple-system,sans-serif;background:#0f0f11;color:#e4e4e7}',
    '.hero{text-align:center;padding:80px 20px 40px}',
    '.hero h1{font-size:3rem;background:linear-gradient(135deg,#818cf8,#6366f1);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:16px}',
    '.hero p{font-size:1.2rem;color:#a1a1aa;max-width:500px;margin:0 auto 32px}',
    '.form{max-width:420px;margin:0 auto;background:#18181b;border:1px solid #27272a;border-radius:12px;padding:24px}',
    '.form input{width:100%;padding:12px;border:1px solid #3f3f46;border-radius:8px;background:#09090b;color:#e4e4e7;font-size:15px;margin-bottom:12px}',
    '.form input:focus{outline:none;border-color:#6366f1}',
    '.form button{width:100%;padding:12px;background:#6366f1;color:white;border:none;border-radius:8px;font-size:15px;font-weight:600;cursor:pointer}',
    '.form button:hover{background:#4f46e5}',
    '.result{display:none;margin-top:16px;padding:16px;background:#09090b;border:1px solid #27272a;border-radius:8px}',
    '.result code{color:#818cf8;word-break:break-all;font-size:14px}',
    '.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px;max-width:800px;margin:40px auto;padding:0 20px}',
    '.feat{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:20px}',
    '.feat h3{color:#818cf8;margin-bottom:8px}.feat p{color:#a1a1aa;font-size:14px}',
    '.how{max-width:600px;margin:20px auto;padding:0 20px}',
    '.how h2{text-align:center;font-size:1.8rem;margin-bottom:20px}',
    '.step{display:flex;gap:16px;margin-bottom:16px;align-items:flex-start}',
    '.sn{background:#6366f1;color:white;width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;flex-shrink:0}',
    '.st h4{margin-bottom:4px}.st p{color:#a1a1aa;font-size:14px}',
    '.pricing{text-align:center;padding:40px 20px}.pricing h2{font-size:2rem;margin-bottom:24px}',
    '.plans{display:flex;gap:20px;justify-content:center;flex-wrap:wrap}',
    '.plan{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:24px;width:280px;text-align:left}',
    '.plan.pro{border-color:#6366f1}',
    '.plan h3{font-size:1.3rem;margin-bottom:4px}',
    '.price{font-size:2rem;font-weight:700;color:#818cf8;margin-bottom:12px}',
    '.plan ul{list-style:none;margin-bottom:16px}',
    '.plan li{padding:4px 0;color:#a1a1aa;font-size:14px}',
    '.plan li::before{content:"\\2713 ";color:#22c55e}',
    'footer{text-align:center;padding:40px;color:#52525b;font-size:13px}',
    '.copy-btn{background:#27272a;border:1px solid #3f3f46;color:#e4e4e7;padding:4px 10px;border-radius:4px;cursor:pointer;font-size:12px;margin-left:8px}',
    '</style></head><body>',
    '<div class="hero"><h1>&#9889; WebhookMail</h1>',
    '<p>Forward any webhook to your email. Instant setup, no code required.</p></div>',
    '<div class="form" id="f">',
    '<input type="email" id="e" placeholder="your@email.com" required>',
    '<input type="text" id="n" placeholder="Endpoint name (optional)">',
    '<button onclick="go()">Create Webhook Endpoint &mdash; Free</button>',
    '<div class="result" id="r">',
    '<p style="margin-bottom:8px;font-size:13px;color:#a1a1aa">Your webhook URL:</p>',
    '<code id="wu"></code><button class="copy-btn" onclick="navigator.clipboard.writeText(document.getElementById(\'wu\').textContent)">Copy</button>',
    '<p style="margin-top:12px;font-size:13px;color:#a1a1aa">Dashboard:</p>',
    '<code id="du"></code></div></div>',
    '<div class="how"><h2>How It Works</h2>',
    '<div class="step"><div class="sn">1</div><div class="st"><h4>Create an endpoint</h4><p>Enter your email, get a unique webhook URL.</p></div></div>',
    '<div class="step"><div class="sn">2</div><div class="st"><h4>Point your service</h4><p>Use the URL as a webhook destination in Stripe, GitHub, Slack, etc.</p></div></div>',
    '<div class="step"><div class="sn">3</div><div class="st"><h4>Get emails</h4><p>Every webhook hit sends a formatted email with headers, body, and metadata.</p></div></div></div>',
    '<div class="features">',
    '<div class="feat"><h3>&#128279; Universal</h3><p>Works with any service that sends webhooks.</p></div>',
    '<div class="feat"><h3>&#128231; Instant Email</h3><p>Formatted email with full request body, headers, and metadata.</p></div>',
    '<div class="feat"><h3>&#128202; Dashboard</h3><p>View webhook history, inspect payloads, track usage.</p></div>',
    '<div class="feat"><h3>&#128274; Private</h3><p>Unique endpoint URLs. No signup required.</p></div></div>',
    '<div class="pricing"><h2>Simple Pricing</h2><div class="plans">',
    '<div class="plan"><h3>Free</h3><div class="price">$0</div><ul>',
    '<li>50 webhooks/month</li><li>1 endpoint</li><li>Email forwarding</li><li>7-day log history</li></ul></div>',
    '<div class="plan pro"><h3>Pro</h3><div class="price">$3<span style="font-size:14px;color:#a1a1aa">/mo</span></div><ul>',
    '<li>Unlimited webhooks</li><li>Unlimited endpoints</li><li>Email forwarding</li><li>30-day log history</li><li>Priority delivery</li><li>Webhook replay</li></ul>',
    '<button style="width:100%;padding:10px;background:#6366f1;color:white;border:none;border-radius:8px;cursor:pointer;font-weight:600" disabled>Coming Soon</button></div>',
    '</div></div>',
    '<footer>WebhookMail &mdash; &copy; 2026</footer>',
    '<script>',
    'async function go(){',
    'var e=document.getElementById("e").value,n=document.getElementById("n").value;',
    'if(!e)return;',
    'var r=await fetch("/api/endpoints",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,name:n})});',
    'var d=await r.json();if(d.error)return alert(d.error);',
    'document.getElementById("wu").textContent=d.webhookUrl;',
    'document.getElementById("du").textContent=d.dashboardUrl;',
    'document.getElementById("r").style.display="block"}',
    '</script></body></html>',
  ].join('\n');
}

export function dashboardPage(endpoint, logs, monthly) {
  const rows = logs.map(l => {
    let body = l.body || '';
    try { body = JSON.stringify(JSON.parse(body), null, 2); } catch {}
    return [
      '<tr>',
      '<td style="padding:8px;border-bottom:1px solid #27272a;color:#a1a1aa;font-size:13px">' + esc(l.created_at) + '</td>',
      '<td style="padding:8px;border-bottom:1px solid #27272a"><span style="background:#6366f1;color:white;padding:2px 8px;border-radius:4px;font-size:12px">' + esc(l.method) + '</span></td>',
      '<td style="padding:8px;border-bottom:1px solid #27272a;font-size:13px;color:#a1a1aa">' + esc(l.source_ip) + '</td>',
      '<td style="padding:8px;border-bottom:1px solid #27272a"><pre style="margin:0;font-size:12px;max-height:100px;overflow:auto;color:#e4e4e7">' + esc(body).slice(0, 500) + '</pre></td>',
      '</tr>',
    ].join('');
  }).join('');

  const emptyRow = '<tr><td colspan="4" style="padding:20px;text-align:center;color:#52525b">No webhooks received yet. Send a POST to the URL above.</td></tr>';

  return [
    '<!DOCTYPE html><html lang="en"><head>',
    '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>Dashboard - ' + esc(endpoint.name || endpoint.id) + '</title>',
    '<style>',
    '*{margin:0;padding:0;box-sizing:border-box}',
    'body{font-family:system-ui,sans-serif;background:#0f0f11;color:#e4e4e7;padding:20px}',
    '.h{max-width:900px;margin:0 auto 20px}',
    '.h h1{font-size:1.5rem;margin-bottom:8px}',
    '.stats{display:flex;gap:16px;margin-bottom:20px}',
    '.stat{background:#18181b;border:1px solid #27272a;border-radius:8px;padding:16px;flex:1}',
    '.stat .l{color:#a1a1aa;font-size:13px}.stat .v{font-size:1.5rem;font-weight:700;color:#818cf8}',
    '.url{background:#18181b;border:1px solid #27272a;border-radius:8px;padding:12px;margin-bottom:20px;word-break:break-all;font-family:monospace;font-size:14px;color:#818cf8}',
    'table{width:100%;max-width:900px;margin:0 auto;border-collapse:collapse}',
    'th{text-align:left;padding:8px;color:#a1a1aa;font-size:13px;border-bottom:1px solid #3f3f46}',
    'a{color:#818cf8}',
    '</style></head><body>',
    '<div class="h">',
    '<h1>&#128202; ' + esc(endpoint.name || 'Webhook Dashboard') + '</h1>',
    '<div class="url">POST ' + BASE_URL + '/hook/' + esc(endpoint.id) + '</div>',
    '<div class="stats">',
    '<div class="stat"><div class="l">This Month</div><div class="v">' + monthly + '</div></div>',
    '<div class="stat"><div class="l">Total</div><div class="v">' + endpoint.webhook_count + '</div></div>',
    '<div class="stat"><div class="l">Tier</div><div class="v">' + esc(endpoint.tier) + '</div></div>',
    '<div class="stat"><div class="l">Email</div><div class="v" style="font-size:14px">' + esc(endpoint.email) + '</div></div>',
    '</div>',
    '<h2 style="margin-bottom:12px">Recent Webhooks</h2>',
    '<table><thead><tr><th>Time</th><th>Method</th><th>Source</th><th>Body</th></tr></thead>',
    '<tbody>' + (rows || emptyRow) + '</tbody></table>',
    '<p style="margin-top:20px;text-align:center"><a href="/">&larr; Back to WebhookMail</a></p>',
    '</div></body></html>',
  ].join('\n');
}
